<?php
namespace Tests\Feature;
use App\Models\Attendance;use App\Models\AttendanceSetting;use App\Models\Department;use App\Models\Employee;use App\Models\Holiday;use App\Models\LeaveRequest;use App\Models\LeaveType;use App\Models\Office;use App\Models\WfhRequest;use Illuminate\Foundation\Testing\RefreshDatabase;use Laravel\Sanctum\Sanctum;use Tests\TestCase;
class LeaveHolidayWfhTest extends TestCase { use RefreshDatabase;
 public function test_employee_can_submit_cancel_and_cannot_overlap_or_read_another_leave():void{$type=LeaveType::create(['name'=>'Annual']);[$employee]=$this->employee();Sanctum::actingAs($employee);$leave=$this->postJson('/api/leaves',['leave_type_id'=>$type->id,'start_date'=>now()->addDays(2)->toDateString(),'end_date'=>now()->addDays(3)->toDateString(),'reason'=>'Trip'])->assertCreated()->json();$this->postJson('/api/leaves',['leave_type_id'=>$type->id,'start_date'=>now()->addDays(3)->toDateString(),'end_date'=>now()->addDays(4)->toDateString()])->assertUnprocessable();$this->postJson('/api/leaves/'.$leave['id'].'/cancel')->assertOk()->assertJsonPath('status','cancelled');[$other]=$this->employee();LeaveRequest::create(['employee_id'=>$other->id,'leave_type_id'=>$type->id,'start_date'=>now()->addDays(5),'end_date'=>now()->addDays(5)]);$this->getJson('/api/leaves')->assertOk()->assertJsonCount(1,'data');}
 public function test_admin_can_approve_leave_and_manage_holidays_while_employee_cannot():void{$type=LeaveType::create(['name'=>'Sick']);[$employee]=$this->employee();$leave=LeaveRequest::create(['employee_id'=>$employee->id,'leave_type_id'=>$type->id,'start_date'=>now()->addDay(),'end_date'=>now()->addDay()]);Sanctum::actingAs($employee);$this->patchJson('/api/admin/leaves/'.$leave->id,['status'=>'approved'])->assertForbidden();[$admin]=$this->employee('ADMIN','super_admin');Sanctum::actingAs($admin);$this->patchJson('/api/admin/leaves/'.$leave->id,['status'=>'approved'])->assertOk()->assertJsonPath('status','approved');$date=now()->addDays(10)->toDateString();$holiday=$this->postJson('/api/admin/holidays',['name'=>'Festival','holiday_date'=>$date])->assertCreated()->json();$this->postJson('/api/admin/holidays',['name'=>'Duplicate','holiday_date'=>$date])->assertUnprocessable();$this->patchJson('/api/admin/holidays/'.$holiday['id'],['active'=>false])->assertOk()->assertJsonPath('active',false);}
 public function test_wfh_is_server_gated_by_eligibility_and_approval_and_respects_optional_rules():void{[$employee,$office]=$this->employee();$settings=$office->attendanceSetting;$settings->update(['wfh_enabled'=>true,'wfh_gps_required'=>false,'wfh_photo_required'=>false,'wfh_approval_required'=>true,'wfh_tracking_enabled'=>false]);Sanctum::actingAs($employee);$this->postJson('/api/attendance/check-in',['mode'=>'wfh'])->assertUnprocessable()->assertJsonValidationErrors('mode');$employee->update(['wfh_eligible'=>true]);$this->postJson('/api/attendance/check-in',['mode'=>'wfh'])->assertUnprocessable()->assertJsonValidationErrors('mode');$request=$this->postJson('/api/wfh-requests',['attendance_date'=>now()->toDateString(),'reason'=>'Remote'])->assertCreated()->json();[$admin]=$this->employee('ADMIN','hr_admin');Sanctum::actingAs($admin);$this->patchJson('/api/admin/wfh-requests/'.$request['id'],['status'=>'approved'])->assertOk();$this->assertDatabaseHas('wfh_requests',['id'=>$request['id'],'status'=>'approved']);Sanctum::actingAs($employee);$employee->refresh();$this->postJson('/api/attendance/check-in',['mode'=>'wfh'])->assertCreated()->assertJsonPath('attendance.status','work_from_home');$attendance=Attendance::first();$this->assertSame('wfh',$attendance->mode);$this->getJson('/api/location/tracking-status')->assertJsonPath('active',false);}
 public function test_holiday_and_configured_week_off_block_attendance_and_calendar_exposes_status():void{[$employee,$office]=$this->employee();$office->attendanceSetting->update(['working_days'=>[]]);Sanctum::actingAs($employee);$this->getJson('/api/calendar')->assertOk()->assertJsonPath('status','week_off');$this->postJson('/api/attendance/check-in',['mode'=>'office','latitude'=>28.6139,'longitude'=>77.2090,'accuracy'=>10])->assertUnprocessable()->assertJsonValidationErrors('attendance');}
 private function employee(string $prefix='EMP',string $role='employee'):array{$department=Department::firstOrCreate(['name'=>'Engineering']);$office=Office::create(['name'=>$prefix.uniqid(),'latitude'=>28.6139,'longitude'=>77.2090,'radius'=>200]);AttendanceSetting::create(['office_id'=>$office->id]);return[Employee::create(['employee_code'=>$prefix.uniqid(),'name'=>$prefix,'email'=>strtolower($prefix).uniqid().'@x.test','mobile'=>'9'.str_pad((string)random_int(1,999999999),9,'0',STR_PAD_LEFT),'password'=>'password','role'=>$role,'department_id'=>$department->id,'office_id'=>$office->id]),$office];}
}
